id: P852C48A0
initial_creation_type: input
source_metadata:
  title: Tulku Thondup
  language: bo
  description: 'Texts by and about Tulku Thondup (sprul sku don grub, b. 1939):'
  volume:
    31673b4471f7439d8d236712b578236f:
      title: Prayer for the Long Life of Tulku Thondup Rinpoche
      parent: Long Life Prayers
created_at: '2022-03-01T01:57:48.611595'
last_modified_at: '2022-03-01T01:57:48.611597'
